Updates project configuration
adds report stage to jenkins

runs prettier

adds jest-junit reporters

runs prettier

adds database migration files

adds database relations

runs prettier

diff --git a/pipeline/Jenkinsfile b/pipeline/Jenkinsfile
--- a/pipeline/Jenkinsfile
+++ b/pipeline/Jenkinsfile
@@ -56,9 +56,6 @@ pipeline {
                 sh "npm run test:ci"
              }
              post {
-                always {
-                    junit 'dist/junit/junit.xml'
-                }
                 success {
                     echo "Unit test success"
                 }
@@ -68,20 +65,39 @@ pipeline {
              }
         }
 
+        stage ("Report") {
+            steps {
+                clover(cloverReportDir: '../dist/coverage', cloverReportFileName: 'clover.xml',
+                  healthyTarget: [methodCoverage: 70, conditionalCoverage: 80, statementCoverage: 80],
+                  unhealthyTarget: [methodCoverage: 50, conditionalCoverage: 50, statementCoverage: 50],
+                  failingTarget: [methodCoverage: 25, conditionalCoverage: 25, statementCoverage: 25]
+                )
+                junit 'dist/junit/junit.xml'
+            }
+            post {
+                success {
+                    echo "Repot success"
+                }
+                failure {
+                    echo "Report failure"
+                }
+            }
+        }
+
         stage ("Publish to Docker Hub") {
             when {
                 branch 'master' // Only run this stage if the branch is 'master'
             }
             steps {
-                sh "docker build -t $DOCKER_IMAGE:tplt-node-server ." 
+                sh "docker build -t $DOCKER_IMAGE:tsks-server ." 
                 withCredentials([usernamePassword(credentialsId: 'DOCKER_HUB_CREDENTIALS', usernameVariable: 'USERNAME', passwordVariable: 'PASSWORD')]) {
                     sh 'echo $PASSWORD | docker login -u $USERNAME --password-stdin'
-                    sh 'docker push $DOCKER_IMAGE:tplt-node-server'
+                    sh 'docker push $DOCKER_IMAGE:tsks-server'
                 }
             }
             post {
                always {
-                    sh 'docker rmi $DOCKER_IMAGE:tplt-node-server || true'
+                    sh 'docker rmi $DOCKER_IMAGE:tsks-server || true'
                } 
             }
         }
